version: "3"
services:
  crudApp:
    image: crud-demo
    ports:
        - "8083:8080"
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://crudApp:27017/Customer
      - MONGODB_STATUS_HOST=crudApp
      - MONGODB_STATUS_PORT=28017
